### ISSUE TITLE
`:checkhealth base` fails

### ISSUE THREAD

**Issue by dwierenga** [NormalNvim/NormalNvim#565]
Running `:checkhealth base` fails with:

```
NormalNvim health stats:
    - ERROR Failed to run healthcheck for "base" plugin. Exception:
      /Users/danwiere/.config/normalnvim/lua/base/health.lua:23: attempt to concatenate local 'normalnvim_version' (a nil value)
```

**Comment by Zeioth** [comment]
![Screenshot_20241204_192055_Termux.jpg](https://github.com/user-attachments/assets/0602898e-a115-4ea0-9d81-d139ec9416da)

@dwierenga what operative system?

I'm going to check the paths, maybe its a windows thing. It runs fine on my smartphone.

**Comment by Zeioth** [comment]
This error was present only if the user download the distro manually, doesn't have `git` installed, and then run `:checkhealth base`.

You are a lucky one.
Fixed! Thanks for reporting!!

**Comment by Zeioth** [comment]
I've find a second weird bug on buffer tabs if the user don't have git installed, but like, you need git so lazy can install the user interface plugin for you in the first place 😅

**Comment by dwierenga** [comment]
Well, I definitely have git installed at `/usr/local/bin/git` and `/usr/local/bin` on my $PATH.

I synced my fork with your repo, blew away my local installation, and re-cloned the entire thing. I re-ran the (dependencies commands)[https://github.com/NormalNvim/NormalNvim/wiki/dependencies] just to make sure.

After all that, `:checkhealth base` still fails with the same error.

**Comment by dwierenga** [comment]
The plot thickens:  when I clone this repo directly via `git clone git@github.com:NormalNvim/NormalNvim.git`, then `:checkhealth base` works fine.  When I clone it with my fork using `git clone git@github.com:dwierenga/NormalNvim.git`, then I get the error message as described above.

why does using a forked repo break the `:checkhealth base` command?

**Comment by Zeioth** [comment]
@dwierenga I just pushed the fix:
https://github.com/NormalNvim/NormalNvim/commit/cb54a4ed3aa2cc3fe3e3faa08042da0e7bd74b13

## More info
* When someone forks NormalNvim, by default the new repo has no version tags.
* If someone immediately runs `:checkhealth`, there was no version to show yet.

We now display `unknown` as version for that border case :)

Thank you for the report!!

**Comment by Zeioth** [comment]
Fixed last one related to #565:
https://github.com/NormalNvim/NormalNvim/commit/d574b7cd929dafea2bfed5204c7eb3b6c079d727

Forked repos, and computers without git should work 100% correctly now.

**Comment by dwierenga** [comment]
Thanks much!  `:checkhealth base` works great now.
